[package]
name = "rusty-wheels"
version = "0.1.0"
authors = ["Ben Clifford <benc@hawaga.org.uk>"]
edition = "2018"

[dependencies]
spidev = {git = "https://github.com/rust-embedded/rust-spidev"}
rand = "0.7.3"
palette = "0.5.0"
sysfs_gpio = "0.5"
signal-hook = "0.1.16"
bdf = "0.6.0"
